"""changed status type

Revision ID: dc91b31b9e6a
Revises: 90c3ad26edf6
Create Date: 2024-11-01 21:49:54.791680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc91b31b9e6a'
down_revision: Union[str, None] = '90c3ad26edf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('IN_PROCESS', 'SHIPPED', 'DELIVED', name='orderstatus'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('IN_PROCESS', 'SHIPPED', 'DELIVED', name='orderstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
